<?php

function uprintmarket_init() {
	drupal_add_js(drupal_get_path('module', 'uprintmarket') .'/uprintmarket.js');
}


function uprintmarket_form_alter(&$form, $form_state, $form_id) {
  // match on form id
  // This is the small add_to_cart form
  if(strstr($form_id, 'uc_product_add_to_cart_form_')) {
    $customqty = '';
    if(isset($form['node']['#value']->field_customqty['und'])){
	$customqty = $form['node']['#value']->field_customqty['und'][0]['value'];
	$options = explode(',', $customqty);
    } else {
	$options = range(1,50);
    }

    if ($form['qty']['#type'] != 'hidden') {
      $form['qty']['#type'] = 'select';
      $form['qty']['#size'] = '1';
      $form['qty']['#multiple'] = FALSE;
      $form['qty']['#options'] = array( null => t('quantity'),);
      $selected = false;
      foreach($options as $i) {
         if(!$selected){
           $form['qty']['#default_value'] = $i;
           $selected = true;
         }
         $form['qty']['#options'][$i] = $i;
      }
    }
  }
}

?>

